# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/delay_pedal/delay_pedal/delay_pedal.srcs/sources_1/ip/fir_hpf_129t_b16/fir_hpf_129t_b16.xci
# IP: The module: 'fir_hpf_129t_b16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fir_hpf_129t_b16/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_hpf_129t_b16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fir_hpf_129t_b16/fir_hpf_129t_b16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_hpf_129t_b16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/delay_pedal/delay_pedal/delay_pedal.srcs/sources_1/ip/fir_hpf_129t_b16/fir_hpf_129t_b16.xci
# IP: The module: 'fir_hpf_129t_b16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fir_hpf_129t_b16/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_hpf_129t_b16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fir_hpf_129t_b16/fir_hpf_129t_b16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_hpf_129t_b16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
