# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/delay_pedal/delay_pedal/delay_pedal.srcs/sources_1/ip/fifo_delay_axis/fifo_delay_axis.xci
# IP: The module: 'fifo_delay_axis' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fifo_delay_axis/fifo_delay_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_axis'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/delay_pedal/delay_pedal/delay_pedal.srcs/sources_1/ip/fifo_delay_axis/fifo_delay_axis.xci
# IP: The module: 'fifo_delay_axis' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/delay_pedal/delay_pedal/delay_pedal.gen/sources_1/ip/fifo_delay_axis/fifo_delay_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_axis'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
